# Generated by Django 5.2.5 on 2025-08-19 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="E.164 preferred (e.g., +15551234567)",
                        max_length=32,
                    ),
                ),
                ("sms_opt_in", models.BooleanField(default=False)),
                (
                    "timezone_name",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone name (e.g., America/Chicago)",
                        max_length=64,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sms_opt_in"], name="accounts_pr_sms_opt_0fa99f_idx"
                    ),
                    models.Index(
                        fields=["phone_number"], name="accounts_pr_phone_n_c27a97_idx"
                    ),
                ],
            },
        ),
    ]
